name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup JDK
        uses: actions/setup-java@v5.7.0
        with:
          java-version: '17'
          distribution: adopt
          check-latest: true
          cache: gradle

      - name: Run code tests
        run: ./gradlew clean check

      - name: Make sure Gradle daemon is stopped
        if: always()
        run: ./gradlew --stop
