name: Dependency Checks

on:
  schedule:
    - cron: 0 8 1 * *
  workflow_dispatch:

jobs:
  owasp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup JDK
        uses: actions/setup-java@v5.3.0
        with:
          java-version: '17'
          distribution: adopt
          check-latest: true
          cache: gradle

      - name: OWASP Dependency Check
        run: ./gradlew clean dependencyCheckAnalyze

      - name: Make sure Gradle daemon is stopped
        if: always()
        run: ./gradlew --stop
